config/routes.rb
Rails.application.routes.draw do
 root 'lifehacks#index'
 resources :lifehacks do
  resources :mylist_rels, only: [:create,:destroy]
  resources :comments, only: [:create,:destroy]
 end
 
 resources :likes
 resources :mylists
 resources :profiles
  get 'followers/index'
  get 'follows/index'
  
 resources :users do
  get 'likes/index'
   resources :relationships, only: [:create,:destroy]
   get 'mylist_names/index'
   get 'followers', on: :member
   get 'follows', on: :member
 end

 resources :mylist_rels, only: [:create]
 resources :mylist_names do
  resources :mylist_rels, only: [:destroy]
  get 'mylist_rels/index'
 end
 
 post 'tops/login'
 get 'tops/logout'
 get 'tops/main'
 get 'get_image/:id', to: 'lifehacks#get_image'
 
 get 'search' => 'lifehacks#search'
 
 get 'like_sort' => 'lifehacks#like_sort'
 
 get 'follow_sort' => 'lifehacks#follow_sort'
 
end

app/models/mylist_rel.rb
class MylistRel < ApplicationRecord
    belongs_to :mylist_name
    belongs_to :lifehack
    
    
end

app/controllers/mylist_rels_controller.rb
class MylistRelsController < ApplicationController
  def index
    @mylists = MylistRel.where(mylist_name_id: params[:mylist_name_id])
    @lifehacks = Lifehack.all
    @mylist_name = MylistName.find(params[:mylist_name_id])
    @user = User.find(@mylist_name.user.id)
    @page_title = "#{@mylist_name.name}"
    render :layout => 'layout/profile'
  end

  def create
    mylist = MylistName.find(params[:mylist_rel][:mylist_name_id])
    lifehack = Lifehack.find(params[:lifehack_id])
    unless mylist.mylisted?(lifehack)
      @mylist_rel = MylistRel.create(mylist_name_id: params[:mylist_rel][:mylist_name_id],lifehack_id: params[:lifehack_id])
      @mylist_rel.save
    else
      flash[:alert] = "すでに追加済です。"
    end
    (redirect_to request.referer) 
  end
  
  def destroy
    mylist = MylistRel.find_by(mylist_name_id: params[:mylist_name_id],lifehack_id: params[:id])
    mylist.destroy
    redirect_to mylist_name_mylist_rels_index_path(params[:mylist_name_id])
  end
  
end

app/helpers/mylist_rels_helper.rb
module MylistRelsHelper
end

app/views/mylist_rels/index.html.erb
<%= stylesheet_link_tag "life/lifehacks", :media => "all" %>

<% @lifehacks.each do |lifehack|  %>
<br>

    <% @mylists.each do |mylist| %>
        <div class="content">
            <% if lifehack.id == mylist.lifehack_id %>
                 
                <%=link_to "#{lifehack.user.name}",profile_path(lifehack.user.id) %>
                
                <h1><%= link_to "#{lifehack.title}",lifehack_path(lifehack) %></h1>
                    <%= ((Time.current - lifehack.time) / 60).to_i.to_s + "分前" %><br>
                
                <%if lifehack.file != nil%>
                <p>
                    <%= image_tag "/get_image/#{lifehack.id}" , :width => '400', :height => '500'%>
                </p>
                <%end%>
                <% if current_user %>
                
                    <% if lifehack.likes.count > 0 %>
                        <%= link_to '♥', like_path(lifehack), method: :delete %>
                        <%= lifehack.likes.count %>
                    <% else %>
                        <%= link_to '♡', likes_path(lifehack_id: lifehack.id), method: :post %>
                        <%= lifehack.likes.count %>
                    <% end %>
                  
                  
                  <%= link_to 'マイリストから外す', mylist_name_mylist_rel_path(@mylist_name.id,lifehack.id),method: :delete %>
                  <br>
          
              <%end%>
              <br>
            <%end%>
        </div>
    <%end%>

<%end%>