config/routes.rb
Rails.application.routes.draw do
 root 'lifehacks#index'
 resources :lifehacks do
  resources :mylist_rels, only: [:create,:destroy]
  resources :comments, only: [:create,:destroy]
 end
 
 resources :likes
 resources :mylists
 resources :profiles
  get 'followers/index'
  get 'follows/index'
  
 resources :users do
  get 'likes/index'
   resources :relationships, only: [:create,:destroy]
   get 'mylist_names/index'
   get 'followers', on: :member
   get 'follows', on: :member
 end

 resources :mylist_rels, only: [:create]
 resources :mylist_names do
  resources :mylist_rels, only: [:destroy]
  get 'mylist_rels/index'
 end
 
 post 'tops/login'
 get 'tops/logout'
 get 'tops/main'
 get 'get_image/:id', to: 'lifehacks#get_image'
 
 get 'search' => 'lifehacks#search'
 
 get 'like_sort' => 'lifehacks#like_sort'
 
 get 'follow_sort' => 'lifehacks#follow_sort'
 
end

app/models/lifehack.rb
class Lifehack < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
    
    has_many :mylist_rels, dependent: :destroy
    
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
    def user
        return User.find_by(id: self.user_id)
    end
    
    def self.search(keyword)
        where(["title like? OR exp like?", "%#{keyword}%", "%#{keyword}%"])
    end
    
end

app/controllers/lifehacks_controller.rb
class LifehacksController < ApplicationController
    
    def index
        @lifehacks = Lifehack.all.order(created_at: :desc)
        @lifehacks = Kaminari.paginate_array(@lifehacks).page(params[:page]).per(5)
        @mylist_rel = MylistRel.new
        @mylist_name = MylistName.new
        @page_title = "ホーム"
    end
    
    def like_sort
        lifehacks = Lifehack.includes(:like_users).sort{|a,b| b.like_users.size <=> a.like_users.size}
        @lifehacks = Kaminari.paginate_array(lifehacks).page(params[:page]).per(5)
        @mylist_rel = MylistRel.new
        @mylist_name = MylistName.new
        @page_title = "いいね順"
        render 'index'
    end
    
    def follow_sort
        @lifehacks = Lifehack.where(user_id:[current_user.followings.ids])
        @lifehacks = Kaminari.paginate_array(@lifehacks).page(params[:page]).per(5)
        @mylist_rel = MylistRel.new
        @mylist_name = MylistName.new
        @page_title = "フォロー中の投稿"
        render 'index'
    end
    
    def new
        @lifehack = Lifehack.new
        @page_title = "新規投稿"
    end
    def create
        
        if params[:lifehack][:file]
            @lifehack = Lifehack.new(user_id: current_user.id, title: params[:lifehack][:title], exp: params[:lifehack][:exp], file: params[:lifehack][:file].read,time: Time.current)
        else
            @lifehack = Lifehack.new(user_id: current_user.id, title: params[:lifehack][:title], exp: params[:lifehack][:exp],time: Time.current)
        end
        if @lifehack.save
        #TODO: ツイートが成功したことをユーザに知らせる
        redirect_to root_path
        else
        render 'new'
        end
    end
    def show
        @lifehack = Lifehack.find(params[:id])
        @user = User.find(@lifehack.user_id)
        @mylist_rel = MylistRel.new
        @mylist_name = MylistName.new
        @comments = @lifehack.comments
        @page_title = "#{@lifehack.title}の詳細ページ"
        if current_user
            @comment = current_user.comments.new
        end
    end
    
    def destroy
        lifehack = Lifehack.find(params[:id])
        lifehack.destroy
        redirect_to root_path
    end
    
    def get_image
        lifehack = Lifehack.find(params[:id]) #↓詳細は説明を後述する
        send_data lifehack.file, disposition: :inline, type: 'image/png'
    end
    def lifehack_params
        params.require(:post).permit(:lifehack_content)
    end
    def search
      @lifehacks = Lifehack.search(params[:keyword])
      @keyword = params[:keyword]
        @lifehacks = Kaminari.paginate_array(@lifehacks).page(params[:page]).per(5)
        @mylist_rel = MylistRel.new
        @mylist_name = MylistName.new
      render "index"
    end
end

app/helpers/lifehacks_helper.rb
module LifehacksHelper
end

app/views/lifehacks/index.html.erb
<%= stylesheet_link_tag "life/lifehacks", :media => "all" %>

<%if current_user%>
  <div class="button02">
  <%= link_to "いいね順に並べる", like_sort_path %>
  <%= link_to "フォロー中のユーザーの投稿", follow_sort_path %>
  </div>
  <%end%>


  <% @lifehacks.each do |e| %>
  <div class="content">
    <p>
      <%=link_to "#{e.user.name}",profile_path(e.user.id) %>
      <h1><%= link_to "#{e.title}",lifehack_path(e) %></h1>
      
      <%if e.file != nil%>
        <p><%= image_tag "/get_image/#{e.id}" , :width => '400', :height => '500'%></p>
      <%end%>
        <% if current_user %>
          <% if e.liked?(current_user) %>
            <%= link_to '♥', like_path(e), method: :delete %>
            <%= e.likes.count %>
          <% else %>
            <%= link_to '♡', likes_path(lifehack_id: e.id), method: :post %>
            <%= e.likes.count %>
        <% end %>
        
        <div class = "mylist">
        <%= form_for @mylist_rel, url: lifehack_mylist_rels_path(e.id), method: :post do |f| %>
          <%= f.label :mylist_name_id,'マイリストに追加' %>
          <%= f.collection_select :mylist_name_id, MylistName.where(user_id: current_user.id), :id, :name %>
          <%= f.submit '追加する' %>
        <%end%>
        <%= form_for @mylist_name,url: mylist_names_path, method: :post do |k| %>
          <%= k.text_field :name,:placeholder => "新規マイリスト" %>
          <%= k.submit '作成' %>
        <%end%>
        </div>
      <% end %>
       <%= ((Time.current - e.time) / 60).to_i.to_s + "分前" %><br>
      </p>
      </div>
  <% end %>

<%= paginate @lifehacks %>

app/views/lifehacks/new.html.erb
   
<%= stylesheet_link_tag "life/lifehacks", :media => "all" %>
<div class="content">
     <% if @lifehack.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @lifehack.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>
<%= form_for @lifehack , url: {action: :create} do |f| %> 
<br>
<%= f.label :title, 'タイトル' %>
<%= f.text_field :title %>
<%= f.label :exp, '内容' %>
<%= f.text_field :exp %>
<p>
<%= f.label :file, 'ファイル' %>
<%= f.file_field :file %>
</p>
<%= f.submit '投稿する' %>

<% end %>
<br>
</div>

app/views/lifehacks/show.html.erb
<%= stylesheet_link_tag "life/lifehacks", :media => "all" %>
 <div class="content">
    <h1><%= @lifehack.title %></h1>
    <p><%= @lifehack.exp %></p>
        <%= ((Time.current - @lifehack.time) / 60).to_i.to_s + "分前" %><br>
    <p>
        <%if @lifehack.file != nil%>
            <%= image_tag "/get_image/#{@lifehack.id}" , :width => '400', :height => '500'%>
        <%end%>
    </p>
    
    <p>
    <p>
        <strong>投稿者:</strong>
        <%= link_to "#{@user.name}",profile_path(@user.id)%>
    </p>
    <% @comments.each do |comment| %>
    <h2>コメント欄</h2>
    <div class = "comment">
    <h4><%= link_to "#{comment.user.name}さん",profile_path(comment.user.id) %></h4>
    <%= comment.comment_content %> 
    <%if comment.user_id == current_user.id %>
    <%=link_to '削除',"/lifehacks/#{@lifehack.id}/comments/#{comment.id}",method: :delete %>
    <%end%>
    <br>s
    <br>
    </div>
    <% end %>
    </p>
    
        <%if current_user%>
            <%= form_with(model:[@lifehack, @comment],url: lifehack_comments_path(@lifehack.id), method: :post) do |f| %>
                <%= f.text_area:comment_content %>
                <%= f.hidden_field :lifehack_id, value: @lifehack.id %>
                <%= f.hidden_field :time, value: Time.current %>
                <br>
                <%= f.submit 'コメントする' %>
            <% end %>
        
            <%= form_for @mylist_rel, url: lifehack_mylist_rels_path(@lifehack.id), method: :post do |f| %>
              <%= f.label :mylist_name_id,'マイリストに追加' %>
              <%= f.collection_select :mylist_name_id, MylistName.where(user_id: current_user.id), :id, :name %>
              <%= f.submit '追加する' %>
            <% end %>
            
            <%= form_for @mylist_name,url: mylist_names_path, method: :post do |k| %>
                <%= k.text_field :name,:placeholder => "新規マイリスト" %>
                <%= k.submit '作成' %>
        <%end%>
        <br>
</div>
<% end %>  