config/routes.rb
Rails.application.routes.draw do
 root 'lifehacks#index'
 resources :lifehacks do
  resources :mylist_rels, only: [:create,:destroy]
  resources :comments, only: [:create,:destroy]
 end
 
 resources :likes
 resources :mylists
 resources :profiles
  get 'followers/index'
  get 'follows/index'
  
 resources :users do
  get 'likes/index'
   resources :relationships, only: [:create,:destroy]
   get 'mylist_names/index'
   get 'followers', on: :member
   get 'follows', on: :member
 end

 resources :mylist_rels, only: [:create]
 resources :mylist_names do
  resources :mylist_rels, only: [:destroy]
  get 'mylist_rels/index'
 end
 
 post 'tops/login'
 get 'tops/logout'
 get 'tops/main'
 get 'get_image/:id', to: 'lifehacks#get_image'
 
 get 'search' => 'lifehacks#search'
 
 get 'like_sort' => 'lifehacks#like_sort'
 
 get 'follow_sort' => 'lifehacks#follow_sort'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :lifehack
end

app/models/lifehack.rb
class Lifehack < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
    
    has_many :mylist_rels, dependent: :destroy
    
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
    def user
        return User.find_by(id: self.user_id)
    end
    
    def self.search(keyword)
        where(["title like? OR exp like?", "%#{keyword}%", "%#{keyword}%"])
    end
    
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :lifehack
end

app/models/mylist.rb
class Mylist < ApplicationRecord
end

app/models/mylist_name.rb
class MylistName < ApplicationRecord
    has_many :mylist_rels, dependent: :destroy
    belongs_to :user
    
    has_many :lifehack_mylist, through: :mylist_rels, source: :lifehack
    
    def mylisted?(lifehack)
        lifehack_mylist.include?(lifehack)
    end
end

app/models/mylist_rel.rb
class MylistRel < ApplicationRecord
    belongs_to :mylist_name
    belongs_to :lifehack
    
    
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :lifehacks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_lifehacks, through: :likes, source: :lifehacks
    
    has_many :mylist_names, dependent: :destroy
    
    has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
    has_many :followers ,through: :passive_relationships, source: :following
    
    
    has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
    has_many :followings, through: :active_relationships, source: :follower
    
    

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
    
    validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }}
    
    validates :name, {presence: true,uniqueness: { case_sensitive: false}}
    
    validates :gen,:age, {presence: :true}
    
    #------------------------------------------------------------------------------------------
    
    #今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)が
    #フォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    def followed_by?(user)
        passive_relationships.find_by(following_id: user.id).present?
    end
    
    
    has_many :lifehacks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_lifehacks, through: :likes, source: :lifehacks
    validates :intro, presence: false, length: { maximum: 50 }
    def liked_by?(lifehack_id)
        likes.where(lifehack_id: lifehack_id).exists?
    end
    def lifehacks
        return Lifehack.where(user_id: self.id)
    end
    has_many :comments
    
    mount_uploader :icon, IconUploader
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def main
        @page_title = "ログインページ"
        render 'login'
    end

    def login
        user = User.find_by(email: params[:email])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
          #TODO: ログイン成功したことをユーザに知らせる
          session[:login_email] = user.email
          redirect_to root_path
        else
          #TODO: エラーメッセージ
          render 'login'
        end
    end

    def logout
        #TODO: ログアウトに成功したことをユーザに知らせる
        session.delete(:login_email)
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lifehacks_helper.rb
module LifehacksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mylist_names_helper.rb
module MylistNamesHelper
end

app/helpers/mylist_rels_helper.rb
module MylistRelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lifehack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id = about >
      <div class = inner >
        
        <p id="alert"><%=  alert %></p>
        
        <h1>
          <h2><%= p "#{@page_title}" %></h2>
        </h1>
        
        <% unless @page_title == "ホーム" %>
        <h3><%=link_to "←戻る",'javascript:history.back()' %></h3>
        <%end%>
        
        <div class=search-form>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword %>
            <%= f.submit "検索" %>
          <% end %>
        </div>
        
        <p>
          <% if current_user %>
          <div class="button02">
            <%= link_to 'ホーム',root_path %>
            
            <%= link_to 'マイページ',profile_path(current_user) %>
            
            <%= link_to '新規投稿',new_lifehack_path %>
          </div>
          <%else%>
          <div class="button02">
            <%= link_to 'ログイン',tops_main_path %>
            <%= link_to '新規ユーザ登録',new_user_path %>
          </div>
          <%end%>
        </p>
         <%= image_tag 'life-hack'%>
          
        <%= yield %>
        <p>
            <% if current_user %>
              <p><%= p "ログイン中です（#{current_user.name}さん）"%></p>
              <div class="button02">
              <%= link_to 'ログアウト',tops_logout_path %>
              </div>
            <% else %>
              <p>ログインしていません</p>
            <% end %>
            <div class="button02">
              <br>
            <%= link_to 'ユーザ一覧', users_path %>
            </div>
        </p>
      </div>
    </section>
    
  </body>
</html>

app/views/layouts/layout/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lifehack-Profile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id = about >
      <div class = inner >
    <p id="alert"><%=  alert %></p>
      
      <h1>
        <h2><%= p "#{@page_title}" %></h2>
      </h1>
      
      <h3><%=link_to "←戻る",'javascript:history.back()' %></h3>
      
      <div class="search-form">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
    
    <div class="button02">
      <%= link_to 'ホーム',root_path %>
      <% if current_user %>
        <%= link_to 'マイページ',profile_path(current_user) %>
        <%= link_to '新規投稿',new_lifehack_path %>
        <%else%>
        <%= link_to 'ログイン',tops_main_path %>
        <%= link_to '新規ユーザ登録',new_user_path %>
      <%end%>
    </div>
    
    <p>
        <h4><%= @user.name %></h4>
        <%= @user.followings.count %>
        <%= link_to "フォロー", follows_user_path(@user.id) %>
        <%= @user.followers.count %>
        <%= link_to "フォロワー", followers_user_path(@user.id) %>
        <%if current_user%>
          <% if current_user.id == @user.id %>
              <%= link_to "マイページ編集", edit_profile_path(@user.id)%>
          <%end%>
        <%end%>
        
        <% if current_user %>
            <% if current_user != @user %>
            <div class="button02">
                <% if @user.followed_by?(current_user) %>
                    <p><%=link_to "フォロー済み", "/users/#{@user.id}/relationships/#{current_user.id}", method: :delete %></p>
                <% else %>
                    <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
                <% end %>
              </div>
            <%end%>
        <%else%>
            <p>このユーザーをフォローするにはログインが必要です</p>
        <%end%>
        
        <h4><%= @user.intro %></h4>
    </p>
    
    <div class="button02">
        <%= link_to 'ライフハック一覧', profile_path(@user.id)%>
        <%= link_to "いいねした投稿", "/users/#{@user.id}/likes/index" %>
        <%= link_to 'マイリスト一覧',user_mylist_names_index_path(@user.id) %>
    </div>
    
    <%= yield %>
    
    <p>
        <% if current_user %>
          <p><%= p "ログイン中です（#{current_user.name}さん）"%></p>
          <div class="button02">
            <%= link_to 'ログアウト',tops_logout_path %>
          </div>
        <% else %>
          <p>ログインしていません</p>
        <% end %>
        <div class="button02">
          <%= link_to 'ユーザ一覧', users_path %>
        </div>
    </p>
     </inner>
    </section>
  </body>
</html>